GCP_PROJECT_ID=""
GCP_REGION=""
GCP_ALLOYDB_CLUSTER=""
GCP_ALLOYDB_INSTANCE=""
GCP_ALLOYDB_DATABASE=""
GCP_ALLOYDB_TABLE=""
VERTEX_EMBEDDING_MODEL=""
VERTEX_LLM=""
LANGCHAIN_PROJECT=""
FIRESTORE_VECTOR_COLLECTION=""
